// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2a-r0caQVn-DpdqV53VP3vA30FxQSLI4',
    appId: '1:326718114264:web:5af19259d857dfe1328aad',
    messagingSenderId: '326718114264',
    projectId: 'itds283-2026-q1',
    authDomain: 'itds283-2026-q1.firebaseapp.com',
    storageBucket: 'itds283-2026-q1.firebasestorage.app',
    measurementId: 'G-SB5QBEXRV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmGhukYYwGreUrIbKy2BNlfbg_lmidhlw',
    appId: '1:326718114264:android:5c4707c5ad57370e328aad',
    messagingSenderId: '326718114264',
    projectId: 'itds283-2026-q1',
    storageBucket: 'itds283-2026-q1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAW4g4uU9END-VdrsHUO98qozDQfioCDI',
    appId: '1:326718114264:ios:9487b7b013e0cdd2328aad',
    messagingSenderId: '326718114264',
    projectId: 'itds283-2026-q1',
    storageBucket: 'itds283-2026-q1.firebasestorage.app',
    iosBundleId: 'com.example.app3dNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAW4g4uU9END-VdrsHUO98qozDQfioCDI',
    appId: '1:326718114264:ios:9487b7b013e0cdd2328aad',
    messagingSenderId: '326718114264',
    projectId: 'itds283-2026-q1',
    storageBucket: 'itds283-2026-q1.firebasestorage.app',
    iosBundleId: 'com.example.app3dNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2a-r0caQVn-DpdqV53VP3vA30FxQSLI4',
    appId: '1:326718114264:web:35aca13824d70285328aad',
    messagingSenderId: '326718114264',
    projectId: 'itds283-2026-q1',
    authDomain: 'itds283-2026-q1.firebaseapp.com',
    storageBucket: 'itds283-2026-q1.firebasestorage.app',
    measurementId: 'G-WXGFKHPFDL',
  );
}
